import { useState } from 'react'
import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css'
import NavBar from '../components/navbar'
import styles from './css/index.module.css';
import Carousel from 'react-bootstrap/Carousel';
import { MdLocationPin } from 'react-icons/md'
import { BsInstagram, BsFacebook, BsFillTelephoneFill, BsWhatsapp } from 'react-icons/bs'
import { AiFillMail } from 'react-icons/ai'

export default function Home() {
  const [items, setItens] = useState([
    {
      altText: 'Slide 1',
      caption: 'Slide 1',
      key: 1,
      src: 'https://picsum.photos/id/123/1200/600'

    },
    {
      altText: 'Slide 2',
      caption: 'Slide 2',
      key: 2,
      src: 'https://picsum.photos/id/456/1200/600'
    },
    {
      altText: 'Slide 3',
      caption: 'Slide 3',
      key: 3,
      src: 'https://picsum.photos/id/678/1200/600'
    }
  ])


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <div className={styles.information}>
          <div>
            <MdLocationPin />
            Rua Costa pinto 234 - Encruzilhada/Recife
          </div>
          <div className={styles.informationContact}>
            <div className={styles.SocialIcons}>
              <i>    <BsInstagram /></i>
              <i>  <BsFacebook /></i>
              <i>  <AiFillMail /></i>



            </div>
            <div className={styles.contactFill}>
              <i>
                <BsFillTelephoneFill />
              </i>
              32441004
            </div>
            <div className={styles.contactFill}>
              <i>
                <BsWhatsapp />
              </i>
              (81)99999-9999
            </div>
          </div>
        </div>
        <NavBar />

        <Carousel className={styles.Carousel} >
          <Carousel.Item className={styles.Carousel}>
            <img
              className="d-block w-100"
              src="https://a.cdn-hotels.com/gdcs/production165/d295/de825d07-0f3f-41e6-b41b-031791c6d729.jpg"
              alt="First slide"
            />
            <Carousel.Caption>
              <h3>First slide label</h3>
              <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
            </Carousel.Caption>
          </Carousel.Item>
          <Carousel.Item className={styles.Carousel}>
            <img
              className="d-block w-100"
              src="http://www.realenergy.com.br/assets/app/indice2.jpg"
              alt="Second slide"
            />

            <Carousel.Caption>
              <h3>Second slide label</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </Carousel.Caption>
          </Carousel.Item>
          <Carousel.Item className={styles.Carousel}>
            <img
              className="d-block w-100"
              src="https://a.cdn-hotels.com/gdcs/production165/d295/de825d07-0f3f-41e6-b41b-031791c6d729.jpg"
              alt="Third slide"
            />

            <Carousel.Caption>
              <h3>Third slide label</h3>
              <p>
                Praesent commodo cursus magna, vel scelerisque nisl consectetur.
              </p>
            </Carousel.Caption>
          </Carousel.Item>
        </Carousel>

        <section>
          <div className={styles.aboutUs}>
            <div className={styles.informationUs}>
              <h3>Quem Somos</h3>
              <article>
                A RealEnergy é uma organização que foi constituída no ano de 1992 tendo como atividade principal a representação de materiais elétricos. Com o decorrer dos anos, iniciou as atividades de engenharia elétrica, participando de programas de eletrificação rural e posteriormente entrando em linhas de transmissão e subestações de energia até 500kV, além de obras de elétrica, mecânica e civil. Atualmente especializou-se em gestão de parques de iluminação pública, detendo tecnologias de ponta com lâmpadas a LED desenvolvidas na região, assim como um sistema de gestão de parques de iluminação pública. Detém em seu quadro técnico profissionais de diversas áreas da engenharia, com especialização em mecânica, industrial, química, elétrica e eletrônica, automação, light design, agronomia, arqueologia, arquitetura, segurança do trabalho e civil, possibilitando ao cliente um mix de engenheiros numa única empresa.
              </article>
            </div>
            <div className={styles.informationImages}>Images</div>
          </div>
        </section>


      </main>

      <footer>

      </footer>
    </div>
  )
}
